- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: configure nginx.conf
  replace:
    path: "/etc/nginx/nginx.conf"
    regexp: '(\s+)worker_connections.*$'
    replace: '\1worker_connections 5000;'
    backup: yes
  notify:
    - restart nginx

- name: Configure proxy
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    mode: 0644
  notify:
    - restart nginx

- name: start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes
