---

# Install mysqld and libaio and Mysql-python
 - name: Inastall mysql
   slackpkg: name="{{ item }}" state=present update_cache=yes
   with_items:
    - mariadb
    - libaio
    - mysqldb-python

# Install python mysqpldb extension
#Install Mysql-python extension from specified package if you have no custom repo.
# - name: Install python mysqldb extension 
#   stat: path=/var/log/packages/Mysql-python
#   register: status
# - copy: src="{{MySQLpython_path}}" dest=/root/Mysql-python.tgz
#   when: not status.stat.exists  
# - command: installpkg /root/Mysql-python.tgz
#   when: not status.stat.exists  

 - name: Install mysqldb
   pip: name=MySQL-python

# Run mysql_install_db
 - name: mysql_install_db
   command: mysql_install_db --user=mysql 
   args:
    creates: /var/lib/mysql/mysql

# Create directory for mysql logs
 - name: Create /var/log/mysql
   file: path=/var/log/mysql state=directory mode=0755

# Set default configuration
 - name: Set configuration
   template: src=my.cnf dest=/etc/my.cnf.d/server.cnf


# Add exec right for rc.mysqld script
 - name: Add mysql to startup
   file: path=/etc/rc.d/rc.mysqld mode=755

# Add network access
 - name: Enable netwroking
   replace: dest=/etc/rc.d/rc.mysqld regexp="^SKIP=" replace="#SKIP"

# Start mysql service
 - name: Start mysql service
   command: /etc/rc.d/rc.mysqld start
   args:
    creates: /var/run/mysql/mysql.pid
   register: out

 - debug: msg="{{out}}"

# - pause: seconds=30
 - wait_for: path=/var/run/mysql/mysql.pid state=present delay=10


# Ansible mysql_secure_installation
 - name: delete anonymous MySQL server user for {{ ansible_hostname }}
   mysql_user: login_user=root login_password='' user="" host="{{ ansible_hostname }}" state="absent"
   ignore_errors: yes

 - name: delete anonymous MySQL server user for localhost
   mysql_user: login_user=root login_password='' user="" state="absent"
   ignore_errors: yes

 - name: remove the MySQL test database
   mysql_db: login_user=root login_password='' db=test state=absent
   ignore_errors: yes

 - name: Change root user password 
   mysql_user: login_user=root
               login_password=''
               name=root
               password={{ mysql_root_password }}
               priv=*.*:ALL,GRANT
               host={{ item }}
   ignore_errors: yes
   with_items:
    - 127.0.0.1
    - localhost

   
