---

# Install mysqld and libaio
 - name: Inastall mysql
   slackpkg: name="{{ item }}" state=present update_cache=yes
   with_items:
    - mariadb
    - libaio

# Run mysql_install_db
 - name: mysql_install_db
   stat: path=/var/lib/mysql/mysql
   register: state
 - command: mysql_install_db --user=mysql 
   when:  not state.stat.exists






# Add exec right for rc.mysqld script
 - name: Add mysql to startup
   file: path=/etc/rc.d/rc.mysqld mode=755

# Start mysql service
 - name: Start mysql service
   command: /etc/rc.d/rc.mysqld start
   register: out

 - debug: msg="{{out}}"

 - copy: src="{{MySQLpython_path}}" dest=/root/Mysql-python.tgz
 - command: installpkg /root/Mysql-python.tgz

 - name: Install mysqlpdb
   pip: name=MySQL-python

# Ansible mysql_secure_installation
 - name: delete anonymous MySQL server user for {{ ansible_hostname }}
   mysql_user: login_user=root login_password='' user="" host="{{ ansible_hostname }}" state="absent"
   ignore_errors: yes

 - name: delete anonymous MySQL server user for localhost
   mysql_user: login_user=root login_password='' user="" state="absent"
   ignore_errors: yes

 - name: remove the MySQL test database
   mysql_db: login_user=root login_password='' db=test state=absent
   ignore_errors: yes

 - name: Change root user password 
   mysql_user: login_user=root
               login_password=''
               name=root
               password={{ mysql_root_password }}
               priv=*.*:ALL,GRANT
               host={{ item }}
   ignore_errors: yes
   with_items:
    - 127.0.0.1
    - localhost

   
