Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |v|
	   v.memory = 2048
  end
  config.vm.provision :shell, :inline => "python --version || ( sudo apt update && sudo apt install -y python )"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end

end
